<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_SupplierController.php" was generated by ProBot AI.
* Date: 5/5/2023 7:48:55 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\Supplier;
use Dotenv\Repository\RepositoryInterface;
use GrahamCampbell\ResultType\Success;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SupplierController extends Controller{
	public function index(){
		return Supplier::all();
	}
	public function create(){
		return view("pages.erp.supplier.create");
	}
	public function store(Request $request){
		//Supplier::create($request->all());
		$supplier = new Supplier;
		$supplier->name=$request->name;
		$supplier->mobile=$request->mobile;
		$supplier->email=$request->email;
date_default_timezone_set("Asia/Dhaka");
		$supplier->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$supplier->updated_at=date('Y-m-d H:i:s');

		$supplier->save();

		return json_encode(['success' => 'Created Successfully.']);
	}
	public function show($id){
		$supplier = Supplier::find($id);
		return json_encode(["suppliar"=>$supplier]);
	}
	public function edit(Supplier $supplier){
		return view("pages.erp.supplier.edit",["supplier"=>$supplier,]);
	}
	public function update(Request $request,$id){
		//Supplier::update($request->all());
		$supplier = Supplier::find($id);
		$supplier->name=$request->name;
		$supplier->mobile=$request->mobile;
		$supplier->email=$request->email;
date_default_timezone_set("Asia/Dhaka");
		$supplier->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$supplier->updated_at=date('Y-m-d H:i:s');

		$supplier->save();

		return json_encode(["success"=>"Successfully Deleted"]);
	}
	public function destroy($id){
		$supplier=Supplier::find($id);
		$supplier->delete();
		return json_encode(["succhess"=>"Successfuly Deleted"]);
	}

	public function get_suppliar_json(){
		$id=$_GET["id"];
		$request=Supplier::find($id);
		return json_encode($request);
	}
}
?>
