<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_TransactionTypeController.php" was generated by ProBot AI.
* Date: 5/4/2023 11:25:52 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\TransactionType;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class TransactionTypeController extends Controller{
	public function index(){
		$transactiontypes = TransactionType::all();
		return response()->json($transactiontypes);
	}
	public function create(){
		return view("pages.erp.transactiontype.create",[]);
	}
	public function store(Request $request)
    {
        $transactiontype = new TransactionType;
		
    	$transactiontype->name=$request->name;
            
        
        $transactiontype->save();
        return response()->json('Product created!');
    }
	public function show($id){
		$transactiontype = TransactionType::find($id);
		return json_encode($transactiontype);
	}
	public function edit(TransactionType $transactiontype){
		return view("pages.erp.transactiontype.edit",["transactiontype"=>$transactiontype,]);
	}
	public function update(Request $request,TransactionType $transactiontype){
		//TransactionType::update($request->all());
		$transactiontype = TransactionType::find($transactiontype->id);
		$transactiontype->name=$request->name;

		$transactiontype->save();

		return json_encode(["Success"=>"Successfully Updated"]);
	}

	public function destroy($id) {
		
		$transactionType=TransactionType::find($id);
		$transactionType->delete();
		return response()->json('Successfully Delete');
	}



}
?>
