<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_StockController.php" was generated by ProBot AI.
* Date: 5/4/2023 11:23:38 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Stock;
use App\Models\Product;
use App\Models\Transaction_Type;
use App\Models\TransactionType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class StockController extends Controller{
	public function index(){
		$stocks = DB::table("stocks as s")
		->join("products as p","s.product_id","=","p.id")
		->join("transaction_types as t","s.transaction_type_id","=","t.id")
		->join("uoms as u","s.uom_id","=","u.id")
		->select("s.*","p.name as pname","t.name as tname","u.name as uname")
		->paginate(5);
		return view("pages.erp.stock.index",["stocks"=>$stocks]);
	}
	public function create(){
		return view("pages.erp.stock.create",["products"=>Product::all(),"transactiontypes"=>TransactionType::all()]);
	}
	public function store(Request $request){
		//Stock::create($request->all());
		$stock = new Stock;
		$stock->product_id=$request->product_id;
		$stock->measure=$request->measure;
		$stock->transaction_type_id=$request->transaction_type_id;
		
date_default_timezone_set("Asia/Dhaka");
		$stock->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$stock->updated_at=date('Y-m-d H:i:s');

		$stock->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){

		// $stock = DB::table("stocks as s")


		$stock = Stock::find($id);
		$stock_details = DB::table('products')
    	->join('stocks', 'stocks.product_id', '=', 'products.id')
		->join('uoms','stocks.uom_id','=','uoms.id')
		->join('transaction_types','stocks.transaction_type_id','=','transaction_types.id')
    	->select('stocks.*', 'products.name as product_name','uoms.name as uname','transaction_types.name as transaction_type')
    	->where('stocks.id', '=', $id)
    	->get();

    	// ->join("products as p","s.product_id","=","p.id")
    	// ->join("transaction_types as t","s.transaction_type_id","=","t.id")
    	// ->join("uoms as u","s.uom_id","=","u.id")
    	
    	// ->select("s.id","p.id","p.name as pname","t.id","t.name as tname","u.id","u.name as uname", DB::raw('SUM(s.measure) as stock'))
    	// ->groupBy('s.product_id')
    	// ->get();

		// $result = DB::table('stocks as s')
		// ->join('products as p', 'p.id', '=', 's.product_id')
		// ->select('s.id as sid', 'p.id', 'p.name', DB::raw('SUM(s.qty) as stock'))
		// ->groupBy('s.product_id')
		// ->get();
		
		return view("pages.erp.stock.show",["stock"=>$stock,"stock_details"=>$stock_details]);
	}
	public function edit(Stock $stock){
		return view("pages.erp.stock.edit",["stock"=>$stock,"products"=>Product::all(),"transaction_types"=>TransactionType::all()]);
	}
	public function update(Request $request,Stock $stock){
		//Stock::update($request->all());
		$stock = Stock::find($stock->id);
		$stock->product_id=$request->product_id;
		$stock->qty=$request->qty;
		$stock->transaction_type_id=$request->transaction_type_id;
		$stock->remark=$request->remark;
date_default_timezone_set("Asia/Dhaka");
		$stock->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$stock->updated_at=date('Y-m-d H:i:s');

		$stock->save();

		return redirect()->route("stock.index")->with('success','Updated Successfully.');
	}
	public function destroy(Stock $stock){
		$stock->delete();
		return redirect()->route("stock.index")->with('success', 'Deleted Successfully.');
	}

	public function report(){
		// $materials=DB::table('stock_view')
		// 		->select('stock_view.*',DB::raw('SUM(total_qty) AS total_qty'))
		// 		->groupBy('name')
		// 		->get();

		$materials=DB::table('stock_view')
		->select('name','total_qty',DB::raw('SUM(total_qty) as total_qty'))
		->groupBy('name')
		->get();
				

				return view('pages.erp.stock.report',["materials"=>$materials]);
	}
}
?>
